### ISSUE TITLE
ACMW-0066: Research for back-end capability.

### ISSUE THREAD

**Issue by EmilyPascua** [acm-csula/ACM-Website-Fall-2019#41]
- Search up technologies that we can use for our back-end feature.
 - I was thinking of using Django for this or Spring.
- General idea:
- Users get to create an account and login.
- They should be able to use any type of email (gmail, yahoo, .edu). The reason for this is that not all members may be students (Let's talk about this though).
- The main idea of the login is for users to accumulate points. Points can be gained through: checking into events (Hiking, bowling, saying hi during a fundraiser etc..), winning the weekly puzzles (these will be from LeetCode using the LeetCode API), or attending workshops. These points then can be redeemed for ACM merch, possible ideas: certificate for most points etc. 
- Question answerer chat system/feature - ask away on a chat system and the chat replies the answer to that question.
 - AWS

**Comment by dtang9** [comment]
These are good ideas to use for next year's (2021) website.

**Comment by dtang9** [comment]
New website: https://github.com/calstatelaacm/acm_portal
