### ISSUE TITLE
ACMW-0021: Add Custom Discord URL

### ISSUE THREAD

**Issue by exelarios** [acm-csula/ACM-Website-Fall-2019#44]
In order to make joining discord sever easier, we should have a redirecting link to the discord server link.

So instead of people typing this:
https://discord.gg/cjYDksF

They can just type this to get automatically redirected.
acm-calstatela.com/discord

I would do it myself, but I don't understand you guys repo structure. lol

**Comment by dtang9** [comment]
https://stackoverflow.com/questions/55103291/redirect-to-third-party-url-using-react-router-dom
